import type { Metadata } from "next";
import { Geist, Geist_Mono, Revalia } from "next/font/google";
import "./globals.css";
import MainNavbar from "./components/MainNavbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const revalia = Revalia({
  variable: "--font-revalia",
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${revalia.variable} antialiased flex min-h-screen flex-col`}
      >
        <MainNavbar />
        {children}
        <div className="sticky bottom-0 mt-auto">
          <Footer />
        </div>
      </body>
    </html>
  );
}
