import type { Metadata } from 'next'
import { Revalia } from 'next/font/google'
import './globals.css'
import MainNavbar from './components/MainNavbar'
import Footer from './components/Footer'

const revalia = Revalia({
    variable: '--font-revalia',
    subsets: ['latin'],
    weight: ['400'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${revalia.variable} flex min-h-screen flex-col antialiased`}
            >
                <MainNavbar />
                {children}
                <div className="sticky bottom-0 mt-auto">
                    <Footer />
                </div>
            </body>
        </html>
    )
}
